import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — SectorData",
};

// DRAFT — Requires legal review before production use.
export default function TermsPage() {
  return (
    <main className="container py-5" style={{ fontFamily: "Arial", maxWidth: 800 }}>
      <h1 style={{ fontWeight: 700, marginBottom: 4 }}>Terms of Service</h1>
      <p style={{ color: "#888", fontSize: 14, marginBottom: 8 }}>Last updated: 2026-05-14</p>
      <div
        className="alert"
        style={{
          background: "#fff3cd",
          border: "1px solid #ffc107",
          borderRadius: 6,
          fontSize: 13,
          marginBottom: 32,
        }}
      >
        <strong>DRAFT</strong> — This document has not been reviewed by legal counsel. Do not rely on
        it in production until formally approved.
      </div>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>1. Acceptance of Terms</h2>
        <p>
          By accessing or using SectorData (the &quot;Service&quot;), you agree to be bound by these
          Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service. These
          Terms apply to all users of the Service.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>2. Service Description</h2>
        <p>
          SectorData is an internal analytics platform provided by Itaú BBA O&amp;G (&quot;IBBA
          O&amp;G&quot;) for monitoring the Brazilian fuel distribution and oil &amp; gas sectors.
          It aggregates data from public sources (ANP and MDIC) and proprietary analyses
          to deliver dashboards, time-series charts, and data exports to authorized users.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>3. Account &amp; Access</h2>
        <p>
          Access to the Service is provisioned exclusively by a designated administrator of IBBA
          O&amp;G. You are responsible for maintaining the confidentiality of your credentials and
          for all activity that occurs under your account. Multi-factor authentication (MFA) is
          strongly recommended and may be mandatory for administrator accounts. Notify the
          administrator immediately if you suspect unauthorized access.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Scrape, crawl, or otherwise systematically extract data from the Service by automated means beyond normal use;</li>
          <li>Reverse-engineer, decompile, or attempt to extract source code from the Service;</li>
          <li>Redistribute, resell, or sublicense any data, report, or analytic output generated by the Service without prior written authorization from IBBA O&amp;G;</li>
          <li>Use the Service for any purpose that violates applicable laws or regulations.</li>
        </ul>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>5. Intellectual Property</h2>
        <p>
          Raw data sourced from ANP, MDIC, and other public agencies remains subject to
          their respective terms. Derived analytics, dashboards, visualizations, and proprietary
          calculations produced by the Service are the exclusive intellectual property of IBBA
          O&amp;G. No license to reproduce or distribute such derived content is granted implicitly
          by accessing the Service.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>6. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranty of
          any kind. IBBA O&amp;G does not warrant the accuracy, completeness, or timeliness of data
          sourced from external agencies. Errors in external source data may be reflected in the
          Service without notice.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by applicable law, IBBA O&amp;G shall not be liable for
          any indirect, incidental, special, consequential, or punitive damages. IBBA O&amp;G&apos;s
          total liability arising out of or related to these Terms shall not exceed the amounts paid
          by you (if any) for use of the Service in the twelve (12) months preceding the claim.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>8. Termination</h2>
        <p>
          IBBA O&amp;G may suspend or revoke your access to the Service at any time, with or without
          cause, with or without notice. Upon termination, your right to use the Service ceases
          immediately.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>9. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the Federative Republic of Brazil. Any disputes
          arising from or related to these Terms shall be subject to the exclusive jurisdiction of
          the courts of the city of São Paulo, State of São Paulo, Brazil.
        </p>
      </section>

      <section className="mb-4">
        <h2 style={{ fontSize: 20, fontWeight: 600 }}>10. Contact</h2>
        <p>
          Questions about these Terms should be directed to:{" "}
          <a href="mailto:eduardo.mendes@itaubba.com">eduardo.mendes@itaubba.com</a>.
        </p>
      </section>
    </main>
  );
}
