-- ─────────────────────────────────────────────────────────────────────────────
-- 20260507000011_add_app_events.sql
--
-- App-level analytics infrastructure for the /admin-analytics dashboard.
-- Access model:
--   - INSERT: blocked via RLS for direct PostgREST; all writes go through
--     `track_event()` SECURITY DEFINER RPC (which calls auth.uid() internally).
--   - SELECT: restricted to callers whose profile.role = 'Admin'.
--   - Analytics RPCs: SECURITY DEFINER, exclude Admins from aggregates,
--     guard against non-Admin callers with RAISE EXCEPTION.
--
-- Design note on last_login:
--   `get_analytics_by_user` computes last_login as
--   MAX(created_at) FILTER (WHERE event_type = 'login') from app_events.
--   If a user has never generated a tracking event (pre-tracking users), the
--   column is NULL. We intentionally do NOT fall back to auth.users.last_sign_in_at
--   to keep the RPC fully within the public schema (no auth schema cross-join
--   inside an authenticated RPC that may have narrow permissions). Callers can
--   display "nunca rastreado" for NULL.
--
-- No pg_cron purge: retention policy deferred pending LGPD decision.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── TABLE ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.app_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text   NOT NULL CHECK (event_type IN ('login', 'page_view', 'export')),
  route      text,
  payload    jsonb  NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes: (user_id, created_at) for per-user timeline + by_user RPC;
--          (event_type, created_at) for KPI aggregates;
--          (route, created_at) partial for dashboard breakdown.
CREATE INDEX IF NOT EXISTS idx_app_events_user_created
  ON public.app_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_events_type_created
  ON public.app_events (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_events_route_created
  ON public.app_events (route, created_at DESC)
  WHERE route IS NOT NULL;

-- ─── RLS ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.app_events ENABLE ROW LEVEL SECURITY;

-- INSERT: deny all direct inserts. track_event() is SECURITY DEFINER and
-- bypasses RLS, so authenticated users can only write via the RPC.
-- (No INSERT policy = deny for anon and authenticated.)

-- SELECT: only Admins may read. Use (select auth.uid()) per Hardening A.
DROP POLICY IF EXISTS "app_events admin read" ON public.app_events;
CREATE POLICY "app_events admin read"
  ON public.app_events
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = (SELECT auth.uid())
        AND role = 'Admin'
    )
  );

-- ─── HELPER: admin guard (inline, no separate function) ──────────────────────
-- Each analytics RPC raises an exception if the caller is not Admin.
-- Implemented inline in each function body.

-- ─── RPC: track_event ────────────────────────────────────────────────────────
-- Ingestion RPC. Called by any authenticated (or even anon) user; silently
-- no-ops when auth.uid() IS NULL. Validates event_type before inserting.

CREATE OR REPLACE FUNCTION public.track_event(
  p_event_type text,
  p_route      text    DEFAULT NULL,
  p_payload    jsonb   DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  -- Silent no-op when called without a session (e.g. server-side render).
  IF auth.uid() IS NULL THEN
    RETURN;
  END IF;

  -- Validate event_type (mirrors the CHECK constraint; belt-and-suspenders).
  IF p_event_type NOT IN ('login', 'page_view', 'export') THEN
    RAISE EXCEPTION 'track_event: invalid event_type "%"', p_event_type;
  END IF;

  INSERT INTO public.app_events (user_id, event_type, route, payload)
  VALUES (auth.uid(), p_event_type, p_route, COALESCE(p_payload, '{}'::jsonb));
END;
$$;

-- ─── RPC: get_analytics_kpis ─────────────────────────────────────────────────
-- Returns top-level KPIs as a single JSON object.
-- DAU/WAU/MAU: distinct users in last 1/7/30 days (Clients only).
-- All other KPIs respect the `period_days` window.

CREATE OR REPLACE FUNCTION public.get_analytics_kpis(
  period_days int DEFAULT 30
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_caller_role text;
  v_result      jsonb;
BEGIN
  -- Admin guard
  SELECT role INTO v_caller_role
  FROM public.profiles
  WHERE id = (SELECT auth.uid());

  IF v_caller_role IS DISTINCT FROM 'Admin' THEN
    RAISE EXCEPTION 'get_analytics_kpis: caller is not an Admin';
  END IF;

  SELECT jsonb_build_object(
    'dau',                  (
      SELECT COUNT(DISTINCT e.user_id)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.created_at >= now() - interval '1 day'
    ),
    'wau',                  (
      SELECT COUNT(DISTINCT e.user_id)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.created_at >= now() - interval '7 days'
    ),
    'mau',                  (
      SELECT COUNT(DISTINCT e.user_id)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.created_at >= now() - interval '30 days'
    ),
    'total_users',          (
      SELECT COUNT(*) FROM public.profiles WHERE role <> 'Admin'
    ),
    'active_users_period',  (
      SELECT COUNT(DISTINCT e.user_id)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.created_at >= now() - (period_days || ' days')::interval
    ),
    'exports_period',       (
      SELECT COUNT(*)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.event_type = 'export'
        AND e.created_at >= now() - (period_days || ' days')::interval
    ),
    'page_views_period',    (
      SELECT COUNT(*)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.event_type = 'page_view'
        AND e.created_at >= now() - (period_days || ' days')::interval
    ),
    'logins_period',        (
      SELECT COUNT(*)
      FROM public.app_events e
      JOIN public.profiles   p ON p.id = e.user_id
      WHERE p.role <> 'Admin'
        AND e.event_type = 'login'
        AND e.created_at >= now() - (period_days || ' days')::interval
    )
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ─── RPC: get_analytics_by_dashboard ─────────────────────────────────────────
-- Engagement breakdown per route. Excludes Admin users.
-- bytes_total: sum of (payload->>'bytes')::bigint for export events.

CREATE OR REPLACE FUNCTION public.get_analytics_by_dashboard(
  period_days int DEFAULT 30
)
RETURNS TABLE(
  route        text,
  page_views   bigint,
  unique_users bigint,
  exports      bigint,
  bytes_total  bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_caller_role text;
BEGIN
  -- Admin guard
  SELECT pr.role INTO v_caller_role
  FROM public.profiles pr
  WHERE pr.id = (SELECT auth.uid());

  IF v_caller_role IS DISTINCT FROM 'Admin' THEN
    RAISE EXCEPTION 'get_analytics_by_dashboard: caller is not an Admin';
  END IF;

  RETURN QUERY
  SELECT
    e.route,
    COUNT(*) FILTER (WHERE e.event_type = 'page_view')                       AS page_views,
    COUNT(DISTINCT e.user_id) FILTER (WHERE e.event_type = 'page_view')      AS unique_users,
    COUNT(*) FILTER (WHERE e.event_type = 'export')                          AS exports,
    COALESCE(
      SUM((e.payload->>'bytes')::bigint) FILTER (WHERE e.event_type = 'export'),
      0
    )                                                                         AS bytes_total
  FROM public.app_events e
  JOIN public.profiles   p ON p.id = e.user_id
  WHERE p.role <> 'Admin'
    AND e.created_at >= now() - (period_days || ' days')::interval
    AND e.route IS NOT NULL
  GROUP BY e.route
  ORDER BY page_views DESC;
END;
$$;

-- ─── RPC: get_analytics_by_user ──────────────────────────────────────────────
-- Per-user engagement summary. Excludes Admins.
-- last_login: MAX(created_at) WHERE event_type = 'login' (NULL if never tracked).
-- top_routes: JSON array of up to 3 {route, views} ordered by views DESC.
-- p_search: case-insensitive substring filter on full_name (empty = no filter).

CREATE OR REPLACE FUNCTION public.get_analytics_by_user(
  period_days int  DEFAULT 30,
  p_search    text DEFAULT ''
)
RETURNS TABLE(
  user_id    uuid,
  full_name  text,
  role       text,
  last_login timestamptz,
  page_views bigint,
  exports    bigint,
  top_routes jsonb
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_caller_role text;
BEGIN
  -- Admin guard
  SELECT pr.role INTO v_caller_role
  FROM public.profiles pr
  WHERE pr.id = (SELECT auth.uid());

  IF v_caller_role IS DISTINCT FROM 'Admin' THEN
    RAISE EXCEPTION 'get_analytics_by_user: caller is not an Admin';
  END IF;

  RETURN QUERY
  SELECT
    p.id                                                                   AS user_id,
    p.full_name,
    p.role,
    MAX(e.created_at) FILTER (WHERE e.event_type = 'login')               AS last_login,
    COUNT(*) FILTER (WHERE e.event_type = 'page_view')                    AS page_views,
    COUNT(*) FILTER (WHERE e.event_type = 'export')                       AS exports,
    (
      SELECT COALESCE(
        jsonb_agg(
          jsonb_build_object('route', sub.route, 'views', sub.views)
          ORDER BY sub.views DESC
        ),
        '[]'::jsonb
      )
      FROM (
        SELECT e2.route, COUNT(*) AS views
        FROM public.app_events e2
        WHERE e2.user_id = p.id
          AND e2.event_type = 'page_view'
          AND e2.route IS NOT NULL
          AND e2.created_at >= now() - (period_days || ' days')::interval
        GROUP BY e2.route
        ORDER BY views DESC
        LIMIT 3
      ) sub
    )                                                                      AS top_routes
  FROM public.profiles p
  LEFT JOIN public.app_events e
    ON e.user_id = p.id
   AND e.created_at >= now() - (period_days || ' days')::interval
  WHERE p.role <> 'Admin'
    AND (
      p_search = ''
      OR p.full_name ILIKE '%' || p_search || '%'
    )
  GROUP BY p.id, p.full_name, p.role
  ORDER BY page_views DESC;
END;
$$;

-- ─── RPC: get_analytics_user_timeline ────────────────────────────────────────
-- Detailed event log for a single user (drill-down). Admin-only.

CREATE OR REPLACE FUNCTION public.get_analytics_user_timeline(
  target_user_id uuid,
  period_days    int DEFAULT 30
)
RETURNS TABLE(
  event_type text,
  route      text,
  payload    jsonb,
  created_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_caller_role text;
BEGIN
  -- Admin guard
  SELECT pr.role INTO v_caller_role
  FROM public.profiles pr
  WHERE pr.id = (SELECT auth.uid());

  IF v_caller_role IS DISTINCT FROM 'Admin' THEN
    RAISE EXCEPTION 'get_analytics_user_timeline: caller is not an Admin';
  END IF;

  RETURN QUERY
  SELECT
    e.event_type,
    e.route,
    e.payload,
    e.created_at
  FROM public.app_events e
  WHERE e.user_id = target_user_id
    AND e.created_at >= now() - (period_days || ' days')::interval
  ORDER BY e.created_at DESC
  LIMIT 500;
END;
$$;

-- ─── RPC: get_analytics_heatmap ──────────────────────────────────────────────
-- Day-of-week x hour heatmap of page_view events. Excludes Admins.
-- DOW: 0=Sunday … 6=Saturday (PostgreSQL EXTRACT(DOW …) convention).

CREATE OR REPLACE FUNCTION public.get_analytics_heatmap(
  period_days int DEFAULT 30
)
RETURNS TABLE(
  dow         int,
  hour        int,
  event_count bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_caller_role text;
BEGIN
  -- Admin guard
  SELECT pr.role INTO v_caller_role
  FROM public.profiles pr
  WHERE pr.id = (SELECT auth.uid());

  IF v_caller_role IS DISTINCT FROM 'Admin' THEN
    RAISE EXCEPTION 'get_analytics_heatmap: caller is not an Admin';
  END IF;

  RETURN QUERY
  SELECT
    EXTRACT(DOW  FROM e.created_at AT TIME ZONE 'America/Sao_Paulo')::int AS dow,
    EXTRACT(HOUR FROM e.created_at AT TIME ZONE 'America/Sao_Paulo')::int AS hour,
    COUNT(*)                                                                AS event_count
  FROM public.app_events e
  JOIN public.profiles   p ON p.id = e.user_id
  WHERE p.role <> 'Admin'
    AND e.event_type = 'page_view'
    AND e.created_at >= now() - (period_days || ' days')::interval
  GROUP BY 1, 2
  ORDER BY 1, 2;
END;
$$;

-- ─── GRANT EXECUTE (authenticated only — not anon) ───────────────────────────
-- track_event: any authenticated user can call (inserts their own event).
-- analytics RPCs: any authenticated user can attempt to call; the Admin guard
--   inside raises exception for non-Admins. This keeps PostgREST happy while
--   the real authorization lives in the SQL body.

GRANT EXECUTE ON FUNCTION public.track_event(text, text, jsonb)              TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_analytics_kpis(int)                     TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_analytics_by_dashboard(int)             TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_analytics_by_user(int, text)            TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_analytics_user_timeline(uuid, int)      TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_analytics_heatmap(int)                  TO authenticated;

-- Revoke from anon (defense-in-depth).
REVOKE EXECUTE ON FUNCTION public.track_event(text, text, jsonb)             FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_analytics_kpis(int)                    FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_analytics_by_dashboard(int)            FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_analytics_by_user(int, text)           FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_analytics_user_timeline(uuid, int)     FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_analytics_heatmap(int)                 FROM anon;
