-- ============================================================================
-- Navios Diesel — table, indexes, RLS, RPC functions
-- ============================================================================

-- ── Table ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.navios_diesel (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collected_at          timestamptz NOT NULL,
    porto                 text NOT NULL,
    status                text NOT NULL,
    navio                 text NOT NULL,
    produto               text NOT NULL DEFAULT 'Óleo Diesel',
    quantidade            double precision,
    unidade               text,
    quantidade_convertida double precision,
    eta                   timestamptz,
    inicio_descarga       timestamptz,
    fim_descarga          timestamptz,
    origem                text,
    berco                 text
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_nd_collected
    ON public.navios_diesel (collected_at);

CREATE INDEX IF NOT EXISTS idx_nd_porto
    ON public.navios_diesel (porto);

CREATE INDEX IF NOT EXISTS idx_nd_collected_porto
    ON public.navios_diesel (collected_at, porto);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nd_unique_row
    ON public.navios_diesel (collected_at, porto, navio);

-- ── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.navios_diesel ENABLE ROW LEVEL SECURITY;

CREATE POLICY "acesso autenticado" ON public.navios_diesel
    FOR SELECT TO authenticated USING (true);

-- ── RPC 1: Latest collection timestamp ───────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_nd_ultima_coleta()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT json_build_object('ultima_coleta', MAX(collected_at))
  FROM public.navios_diesel;
$$;

-- ── RPC 2: All distinct collection timestamps ────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_nd_coletas_distintas()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(ts ORDER BY ts DESC), '[]'::json)
  FROM (SELECT DISTINCT collected_at AS ts FROM public.navios_diesel) sub;
$$;

-- ── RPC 3: Vessel rows for a given snapshot ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_nd_navios(p_collected_at timestamptz)
RETURNS SETOF public.navios_diesel LANGUAGE sql SECURITY DEFINER AS $$
  SELECT * FROM public.navios_diesel
  WHERE collected_at = p_collected_at
  ORDER BY porto, status, navio;
$$;

-- ── RPC 4: Per-port aggregation for a given snapshot ─────────────────────────
CREATE OR REPLACE FUNCTION public.get_nd_resumo_portos(p_collected_at timestamptz)
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(row_to_json(sub)), '[]'::json)
  FROM (
    SELECT
      porto,
      COUNT(*)::int AS total_navios,
      COALESCE(SUM(quantidade), 0) AS total_quantidade,
      COALESCE(SUM(quantidade_convertida), 0) AS total_convertida
    FROM public.navios_diesel
    WHERE collected_at = p_collected_at
    GROUP BY porto
    ORDER BY total_navios DESC
  ) sub;
$$;
