-- ============================================================================
-- Legacy: price_bands — table, indexes, RLS, RPC
--
-- Mirrors sql/create_price_bands.sql, which was applied directly via the
-- Supabase Dashboard before versioned migrations were adopted.
--
-- All DDL is idempotent (IF NOT EXISTS / CREATE OR REPLACE / policy guard).
-- This migration registers the existing schema in supabase_migrations so that
-- `supabase db push` no longer treats these objects as untracked.
--
-- Drift vs prod:
--   - get_price_bands_data(text): prod has SET search_path = public, pg_temp
--     applied via ALTER FUNCTION in 20260505000002_hardening_b_search_path.sql.
--     The CREATE OR REPLACE below includes SET search_path inline (equivalent).
--     Also adds STABLE qualifier (safe — function has no side-effects).
--   - No other drift detected between sql/ definition and prod schema.
-- ============================================================================

-- ── Table ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.price_bands (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date                        DATE    NOT NULL,
  product                     TEXT    NOT NULL,   -- 'Gasoline' | 'Diesel'
  bba_import_parity           NUMERIC(10,4),      -- IBBA for Gasoline, BBA for Diesel
  bba_import_parity_w_subsidy NUMERIC(10,4),      -- Diesel only
  bba_export_parity           NUMERIC(10,4),
  petrobras_price             NUMERIC(10,4),
  petrobras_price_w_subsidy   NUMERIC(10,4),      -- reserved, not yet used
  CONSTRAINT uq_price_bands_product_date UNIQUE (product, date)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_pb_product_date
  ON public.price_bands (product, date);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE public.price_bands ENABLE ROW LEVEL SECURITY;

DO $policy$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'price_bands'
      AND policyname = 'acesso autenticado'
  ) THEN
    CREATE POLICY "acesso autenticado" ON public.price_bands
      FOR SELECT TO authenticated USING (true);
  END IF;
END
$policy$;

-- ── RPC ───────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_price_bands_data(
  p_product text DEFAULT NULL
)
RETURNS SETOF public.price_bands
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT *
  FROM public.price_bands
  WHERE (p_product IS NULL OR product = p_product)
  ORDER BY date;
$$;
