-- ============================================================================
-- Discovery-run log for the AIS Import Radar.
--
-- Motivation: the calendar and "last seen" columns are derived from surviving
-- candidates. When a sweep captures only cabotage or non-oil-tankers, all
-- those rows are filtered out and the UI looks stale even though the pipeline
-- ran fine. This table records every sweep independently so the dashboard
-- can always show when the radar last updated, regardless of what passed the
-- filters.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.discovery_runs (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ran_at               timestamptz NOT NULL DEFAULT now(),
    listen_seconds       int,
    msgs_total           int,      -- raw ShipStaticData msgs received
    br_matches           int,      -- msgs with BR-port destination
    unique_imos          int,      -- distinct IMOs among br_matches
    cabotage_skipped     int,      -- skipped because origin is Brazilian
    non_tanker_skipped   int,      -- skipped because ship type isn't oil tanker
    candidates_written   int,      -- rows upserted into import_candidates
    positions_written    int       -- rows appended to candidate_positions
);

CREATE INDEX IF NOT EXISTS idx_dr_ran_at ON public.discovery_runs (ran_at DESC);

ALTER TABLE public.discovery_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.discovery_runs
    FOR SELECT TO authenticated USING (true);

-- RPC: most recent sweep (whatever the outcome)
CREATE OR REPLACE FUNCTION public.get_ic_last_run()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT row_to_json(x) FROM (
    SELECT
      ran_at, listen_seconds,
      msgs_total, br_matches, unique_imos,
      cabotage_skipped, non_tanker_skipped,
      candidates_written, positions_written
    FROM public.discovery_runs
    ORDER BY ran_at DESC
    LIMIT 1
  ) x;
$$;
