-- ============================================================================
-- D&G Margins — table, indexes, RLS, RPC functions
-- ============================================================================

-- ── Table ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.d_g_margins (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_type                       text NOT NULL,        -- 'Diesel B' | 'Gasoline C'
    week                            text NOT NULL,        -- '13/2026'
    distribution_and_resale_margin  numeric,
    state_tax                       numeric,
    federal_tax                     numeric,
    biofuel_component               numeric,              -- Biodiesel (Diesel) | Anhydrous Ethanol (Gasoline)
    base_fuel                       numeric,              -- Diesel A | Gasoline A
    total                           numeric,
    UNIQUE(fuel_type, week)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_dgm_fuel_week
    ON public.d_g_margins (fuel_type, week);

-- ── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.d_g_margins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "acesso autenticado" ON public.d_g_margins
    FOR SELECT TO authenticated USING (true);

-- ── RPC 1: Data rows ordered chronologically ─────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_dg_margins_data(
    p_fuel_type text DEFAULT NULL
)
RETURNS SETOF public.d_g_margins LANGUAGE sql SECURITY DEFINER AS $$
  SELECT *
  FROM public.d_g_margins
  WHERE (p_fuel_type IS NULL OR fuel_type = p_fuel_type)
  ORDER BY
    SPLIT_PART(week, '/', 2)::int,
    SPLIT_PART(week, '/', 1)::int;
$$;

-- ── RPC 2: Distinct fuel_types + sorted weeks for UI filters ─────────────────
CREATE OR REPLACE FUNCTION public.get_dg_margins_filters()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT json_build_object(
    'fuel_types', (
      SELECT COALESCE(json_agg(DISTINCT fuel_type ORDER BY fuel_type), '[]'::json)
      FROM public.d_g_margins
    ),
    'weeks', (
      SELECT COALESCE(
        json_agg(week ORDER BY SPLIT_PART(week, '/', 2)::int, SPLIT_PART(week, '/', 1)::int),
        '[]'::json
      )
      FROM (SELECT DISTINCT week FROM public.d_g_margins) w
    )
  );
$$;
