-- ============================================================================
-- AIS tracking — vessel registry, positions, port polygons, arrivals
-- ============================================================================

-- ── Extend navios_diesel with AIS identifiers ────────────────────────────────
ALTER TABLE public.navios_diesel
    ADD COLUMN IF NOT EXISTS imo  text,
    ADD COLUMN IF NOT EXISTS mmsi text;

CREATE INDEX IF NOT EXISTS idx_nd_imo  ON public.navios_diesel (imo);
CREATE INDEX IF NOT EXISTS idx_nd_mmsi ON public.navios_diesel (mmsi);

-- ── vessel_registry: canonical name ↔ IMO ↔ MMSI ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.vessel_registry (
    imo           text PRIMARY KEY,
    mmsi          text,
    name          text NOT NULL,
    name_norm     text GENERATED ALWAYS AS (upper(regexp_replace(name, '[^A-Za-z0-9]', '', 'g'))) STORED,
    ship_type     text,
    flag          text,
    last_seen_at  timestamptz,
    first_seen_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vr_name_norm ON public.vessel_registry (name_norm);
CREATE INDEX IF NOT EXISTS idx_vr_mmsi      ON public.vessel_registry (mmsi);

ALTER TABLE public.vessel_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.vessel_registry
    FOR SELECT TO authenticated USING (true);

-- ── vessel_positions: time-series of AIS positions ───────────────────────────
CREATE TABLE IF NOT EXISTS public.vessel_positions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imo         text,
    mmsi        text,
    ts          timestamptz NOT NULL,
    lat         double precision NOT NULL,
    lon         double precision NOT NULL,
    sog         double precision,
    cog         double precision,
    nav_status  text,
    inside_port text,
    CONSTRAINT vp_identifier_present CHECK (imo IS NOT NULL OR mmsi IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_vp_imo_time  ON public.vessel_positions (imo, ts DESC);
CREATE INDEX IF NOT EXISTS idx_vp_mmsi_time ON public.vessel_positions (mmsi, ts DESC);
CREATE INDEX IF NOT EXISTS idx_vp_inside    ON public.vessel_positions (inside_port) WHERE inside_port IS NOT NULL;

ALTER TABLE public.vessel_positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.vessel_positions
    FOR SELECT TO authenticated USING (true);

-- ── port_polygons: bounding polygon for each monitored port ──────────────────
CREATE TABLE IF NOT EXISTS public.port_polygons (
    slug       text PRIMARY KEY,
    name       text NOT NULL,
    polygon    jsonb NOT NULL,
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.port_polygons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.port_polygons
    FOR SELECT TO authenticated USING (true);

-- Seed initial polygons (approximate rectangles — refine later)
INSERT INTO public.port_polygons (slug, name, polygon) VALUES
    ('santos',        'Porto de Santos',        '{"type":"Polygon","coordinates":[[[-46.36,-24.00],[-46.25,-24.00],[-46.25,-23.88],[-46.36,-23.88],[-46.36,-24.00]]]}'::jsonb),
    ('itaqui',        'Porto de Itaqui',        '{"type":"Polygon","coordinates":[[[-44.40,-2.60],[-44.30,-2.60],[-44.30,-2.52],[-44.40,-2.52],[-44.40,-2.60]]]}'::jsonb),
    ('paranagua',     'Porto de Paranaguá',     '{"type":"Polygon","coordinates":[[[-48.58,-25.55],[-48.45,-25.55],[-48.45,-25.48],[-48.58,-25.48],[-48.58,-25.55]]]}'::jsonb),
    ('sao_sebastiao', 'Porto de São Sebastião', '{"type":"Polygon","coordinates":[[[-45.42,-23.82],[-45.35,-23.82],[-45.35,-23.76],[-45.42,-23.76],[-45.42,-23.82]]]}'::jsonb),
    ('suape',         'Porto de Suape',         '{"type":"Polygon","coordinates":[[[-34.98,-8.42],[-34.92,-8.42],[-34.92,-8.35],[-34.98,-8.35],[-34.98,-8.42]]]}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

-- ── port_arrivals: detected entry/exit events ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.port_arrivals (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imo         text,
    mmsi        text,
    vessel_name text,
    port_slug   text NOT NULL REFERENCES public.port_polygons(slug),
    entered_at  timestamptz NOT NULL,
    exited_at   timestamptz,
    detected_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pa_open
    ON public.port_arrivals (imo, port_slug) WHERE exited_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pa_port_time
    ON public.port_arrivals (port_slug, entered_at DESC);

ALTER TABLE public.port_arrivals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.port_arrivals
    FOR SELECT TO authenticated USING (true);

-- ── RPC: latest AIS position for each vessel in a given navios_diesel snapshot
CREATE OR REPLACE FUNCTION public.get_ais_positions_latest(p_collected_at timestamptz)
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  WITH navios AS (
    SELECT DISTINCT navio, imo, mmsi
    FROM public.navios_diesel
    WHERE collected_at = p_collected_at
  ),
  resolved AS (
    -- prefer explicit imo on the row; otherwise look up by normalised name
    SELECT
      n.navio,
      COALESCE(n.imo, r.imo)   AS imo,
      COALESCE(n.mmsi, r.mmsi) AS mmsi
    FROM navios n
    LEFT JOIN public.vessel_registry r
      ON r.name_norm = upper(regexp_replace(n.navio, '[^A-Za-z0-9]', '', 'g'))
  ),
  latest AS (
    SELECT DISTINCT ON (vp.imo, vp.mmsi)
      vp.imo, vp.mmsi, vp.ts, vp.lat, vp.lon, vp.sog, vp.cog, vp.nav_status, vp.inside_port
    FROM public.vessel_positions vp
    WHERE vp.ts >= now() - interval '7 days'
    ORDER BY vp.imo, vp.mmsi, vp.ts DESC
  )
  SELECT COALESCE(json_agg(row_to_json(x)), '[]'::json) FROM (
    SELECT
      r.navio, r.imo, r.mmsi,
      l.ts, l.lat, l.lon, l.sog, l.cog, l.nav_status, l.inside_port
    FROM resolved r
    LEFT JOIN latest l
      ON (r.imo IS NOT NULL AND l.imo = r.imo)
      OR (r.imo IS NULL AND r.mmsi IS NOT NULL AND l.mmsi = r.mmsi)
    WHERE l.lat IS NOT NULL
  ) x;
$$;

-- ── RPC: open port arrivals (vessels currently inside a port polygon) ────────
CREATE OR REPLACE FUNCTION public.get_ais_arrivals_open()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(row_to_json(x) ORDER BY x.entered_at DESC), '[]'::json) FROM (
    SELECT
      pa.imo,
      pa.mmsi,
      COALESCE(vr.name, pa.vessel_name) AS vessel_name,
      pa.port_slug,
      pp.name AS port_name,
      pa.entered_at,
      pa.exited_at,
      pa.detected_at
    FROM public.port_arrivals pa
    LEFT JOIN public.vessel_registry vr ON vr.imo = pa.imo
    LEFT JOIN public.port_polygons pp ON pp.slug = pa.port_slug
    WHERE pa.exited_at IS NULL
  ) x;
$$;

-- ── RPC: all port polygons (GeoJSON) ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_port_polygons()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(row_to_json(x) ORDER BY x.slug), '[]'::json) FROM (
    SELECT slug, name, polygon FROM public.port_polygons
  ) x;
$$;
