-- ============================================================================
-- Historical position trail for AIS import candidates.
--
-- `import_candidates` keeps only the *latest* last_seen_* — each discovery
-- run overwrites the previous position. This table accumulates every
-- observation so the vessel's trajectory from origin hub to Brazilian
-- destination can be reconstructed later (route visualisation, arrival
-- latency analytics, etc.). Not exposed in the main candidates table;
-- queryable per-IMO via a dedicated RPC.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.candidate_positions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imo               text NOT NULL,
    mmsi              text,
    ts                timestamptz NOT NULL,
    lat               double precision NOT NULL,
    lon               double precision NOT NULL,
    confidence_score  int,
    destination_slug  text,
    UNIQUE (imo, ts)
);

CREATE INDEX IF NOT EXISTS idx_cp_imo_ts  ON public.candidate_positions (imo, ts DESC);
CREATE INDEX IF NOT EXISTS idx_cp_ts      ON public.candidate_positions (ts DESC);

ALTER TABLE public.candidate_positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.candidate_positions
    FOR SELECT TO authenticated USING (true);

-- RPC: chronological position trail for one vessel (used by future route viz)
CREATE OR REPLACE FUNCTION public.get_candidate_trail(p_imo text, p_limit int DEFAULT 500)
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(row_to_json(x) ORDER BY x.ts ASC), '[]'::json) FROM (
    SELECT ts, lat, lon, confidence_score, destination_slug
    FROM public.candidate_positions
    WHERE imo = p_imo
    ORDER BY ts DESC
    LIMIT p_limit
  ) x;
$$;
