-- ============================================================================
-- ANP Preços de Distribuição — table, indexes, RLS, RPC functions
-- Source: https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-de-distribuicao-de-combustiveis
-- Granularidades: Brasil semanal (combustíveis líquidos), UF mensal (GLP P13),
--                 Município mensal (combustíveis líquidos, ~459 municípios)
-- ============================================================================

-- ── Table ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.anp_precos_distribuicao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_referencia DATE    NOT NULL,        -- início da semana (semanal) ou 1º dia do mês (mensal)
    periodicidade   TEXT    NOT NULL CHECK (periodicidade IN ('semanal', 'mensal')),
    produto         TEXT    NOT NULL,        -- 'Gasolina Comum', 'Etanol Hidratado', 'Diesel S10', 'Diesel S500', 'GNV', 'GLP P13'
    granularidade   TEXT    NOT NULL CHECK (granularidade IN ('brasil', 'uf', 'municipio')),
    uf              TEXT,                    -- NULL quando granularidade = 'brasil'
    municipio       TEXT,                    -- NULL quando granularidade != 'municipio'
    preco_medio     NUMERIC(10,4) NOT NULL,
    preco_minimo    NUMERIC(10,4),
    preco_maximo    NUMERIC(10,4),
    numero_postos   INT,                     -- cobertura de pesquisa (NULL para Brasil)
    unidade         TEXT    NOT NULL DEFAULT 'R$/L',  -- 'R$/L' líquidos, 'R$/13kg' GLP, 'R$/m³' GNV
    fonte_arquivo   TEXT,                    -- nome do XLSX original para rastreabilidade
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_anp_precos_distribuicao
        UNIQUE (data_referencia, produto, granularidade, uf, municipio)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Range query on period slider
CREATE INDEX IF NOT EXISTS idx_anp_precos_dist_data
    ON public.anp_precos_distribuicao (data_referencia);

-- Primary lookup: series filtered by produto + granularidade, ordered by date DESC
CREATE INDEX IF NOT EXISTS idx_anp_precos_dist_lookup
    ON public.anp_precos_distribuicao (produto, granularidade, data_referencia DESC);

-- Partial index for UF-level queries
CREATE INDEX IF NOT EXISTS idx_anp_precos_dist_uf
    ON public.anp_precos_distribuicao (uf)
    WHERE uf IS NOT NULL;

-- Partial index for municipality-level queries
CREATE INDEX IF NOT EXISTS idx_anp_precos_dist_municipio
    ON public.anp_precos_distribuicao (municipio)
    WHERE municipio IS NOT NULL;

-- ── RLS ───────────────────────────────────────────────────────────────────────

ALTER TABLE public.anp_precos_distribuicao ENABLE ROW LEVEL SECURITY;

-- Authenticated users read all rows
CREATE POLICY "acesso autenticado"
    ON public.anp_precos_distribuicao
    FOR SELECT TO authenticated USING (true);

-- Service role (pipelines) can write
CREATE POLICY "service role full access"
    ON public.anp_precos_distribuicao
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── module_visibility ─────────────────────────────────────────────────────────

INSERT INTO public.module_visibility (module_slug, is_visible_for_clients)
VALUES ('anp-precos-distribuicao', true)
ON CONFLICT (module_slug) DO NOTHING;

-- ── RPC: filter options ───────────────────────────────────────────────────────
-- Returns JSONB with distinct values for all filter axes plus date range.
-- Granularidades ordered canonically: brasil → uf → municipio.

CREATE OR REPLACE FUNCTION public.get_anp_precos_distribuicao_filtros()
RETURNS jsonb
LANGUAGE sql SECURITY DEFINER
SET search_path = public
AS $$
    SELECT jsonb_build_object(
        'produtos', (
            SELECT COALESCE(jsonb_agg(DISTINCT produto ORDER BY produto), '[]'::jsonb)
            FROM public.anp_precos_distribuicao
        ),
        'granularidades', (
            SELECT COALESCE(
                jsonb_agg(g ORDER BY
                    CASE g
                        WHEN 'brasil'    THEN 1
                        WHEN 'uf'        THEN 2
                        WHEN 'municipio' THEN 3
                        ELSE 4
                    END
                ),
                '[]'::jsonb
            )
            FROM (
                SELECT DISTINCT granularidade AS g
                FROM public.anp_precos_distribuicao
            ) sub
        ),
        'ufs', (
            SELECT COALESCE(jsonb_agg(DISTINCT uf ORDER BY uf), '[]'::jsonb)
            FROM public.anp_precos_distribuicao
            WHERE uf IS NOT NULL
        ),
        'municipios', (
            SELECT COALESCE(jsonb_agg(DISTINCT municipio ORDER BY municipio), '[]'::jsonb)
            FROM public.anp_precos_distribuicao
            WHERE municipio IS NOT NULL
        ),
        'data_min', (SELECT MIN(data_referencia) FROM public.anp_precos_distribuicao),
        'data_max', (SELECT MAX(data_referencia) FROM public.anp_precos_distribuicao)
    );
$$;

-- ── RPC: time series ──────────────────────────────────────────────────────────
-- Returns one row per (data_referencia, local) for the selected produto +
-- granularidade combination.  p_locais filters by UF or município depending
-- on the chosen granularidade; ignored when granularidade = 'brasil'.

CREATE OR REPLACE FUNCTION public.get_anp_precos_distribuicao_serie(
    p_produto       text,
    p_granularidade text,
    p_locais        text[]  DEFAULT NULL,
    p_data_inicio   date    DEFAULT NULL,
    p_data_fim      date    DEFAULT NULL
)
RETURNS TABLE(
    data_referencia date,
    local           text,
    preco_medio     numeric,
    preco_minimo    numeric,
    preco_maximo    numeric,
    unidade         text
)
LANGUAGE sql SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        data_referencia,
        CASE p_granularidade
            WHEN 'brasil'    THEN 'Brasil'
            WHEN 'uf'        THEN uf
            WHEN 'municipio' THEN municipio
        END AS local,
        preco_medio,
        preco_minimo,
        preco_maximo,
        unidade
    FROM public.anp_precos_distribuicao
    WHERE produto       = p_produto
      AND granularidade = p_granularidade
      AND (p_data_inicio IS NULL OR data_referencia >= p_data_inicio)
      AND (p_data_fim    IS NULL OR data_referencia <= p_data_fim)
      AND (
          p_locais IS NULL
          OR (p_granularidade = 'uf'        AND uf        = ANY(p_locais))
          OR (p_granularidade = 'municipio' AND municipio = ANY(p_locais))
          OR  p_granularidade = 'brasil'
      )
    ORDER BY data_referencia,
             CASE p_granularidade
                 WHEN 'brasil'    THEN 'Brasil'
                 WHEN 'uf'        THEN uf
                 WHEN 'municipio' THEN municipio
             END;
$$;

-- ── RPC: export count ─────────────────────────────────────────────────────────
-- Returns row count for the given filter combination.  Used by ExportModal
-- live-size calculator (Tier 2 export UX).  NULL parameters skip that axis.

CREATE OR REPLACE FUNCTION public.get_anp_precos_distribuicao_export_count(
    p_produtos        text[]  DEFAULT NULL,
    p_granularidades  text[]  DEFAULT NULL,
    p_locais          text[]  DEFAULT NULL,
    p_data_inicio     date    DEFAULT NULL,
    p_data_fim        date    DEFAULT NULL
)
RETURNS int
LANGUAGE sql SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COUNT(*)::int
    FROM public.anp_precos_distribuicao
    WHERE
        (p_produtos       IS NULL OR produto       = ANY(p_produtos))
        AND (p_granularidades IS NULL OR granularidade = ANY(p_granularidades))
        AND (p_data_inicio IS NULL OR data_referencia >= p_data_inicio)
        AND (p_data_fim    IS NULL OR data_referencia <= p_data_fim)
        AND (
            p_locais IS NULL
            OR uf        = ANY(p_locais)
            OR municipio = ANY(p_locais)
        );
$$;
