-- ============================================================================
-- Diesel Imports — AIS Radar
--
-- Table `import_candidates`: tankers worldwide whose AIS ShipStaticData
-- broadcast declares a destination at one of the 5 monitored Brazilian
-- ports, enriched with VesselFinder port-call data (last port, draft,
-- vessel type) to infer cargo likelihood.
--
-- Purpose: give 10-30 days early warning of vessels heading to Brazil
-- with diesel, BEFORE they appear in the port authorities' public
-- line-up scraping (which only publishes ~3-7 days ahead of ETA).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.import_candidates (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identity
    imo             text UNIQUE NOT NULL,
    mmsi            text,
    navio           text NOT NULL,
    flag            text,

    -- Classification (AIS ship type + VF-reported type string)
    ship_type_code  int,                 -- AIS type (80-89 = tanker)
    ship_type       text,                -- VF type e.g. "Chemical/Oil Products Tanker"
    length_m        numeric,
    dwt             int,

    -- Destination declared via AIS
    destination_raw  text,               -- As broadcast (e.g. "BRITQ", "BR ITQ", "SANTOS")
    destination_slug text,               -- Mapped to our 5 monitored ports
    destination_port_name text,
    eta              timestamptz,

    -- Origin (last port call via VesselFinder pcext)
    origin_port_name text,
    origin_locode    text,
    origin_country   text,
    origin_is_product_hub boolean,
    departure_ts     timestamptz,

    -- Cargo inference signals
    current_draught_m numeric,           -- Current AIS-reported draft
    max_draught_m     numeric,           -- Design/max draft (from VF)
    is_loaded         boolean,           -- current_draught / max_draught > 0.7

    -- Confidence (0-100) composite score + signal breakdown
    confidence_score int,
    signals          jsonb,              -- {destination_ok, origin_hub, tanker_ok, loaded_ok, ...}

    -- Lifecycle
    first_seen_at    timestamptz DEFAULT now(),
    last_seen_at     timestamptz,
    status           text NOT NULL DEFAULT 'active',
                     -- active | in_lineup | arrived | dismissed
    in_lineup_since  timestamptz
);

CREATE INDEX IF NOT EXISTS idx_ic_status   ON public.import_candidates (status);
CREATE INDEX IF NOT EXISTS idx_ic_dest     ON public.import_candidates (destination_slug);
CREATE INDEX IF NOT EXISTS idx_ic_eta      ON public.import_candidates (eta);
CREATE INDEX IF NOT EXISTS idx_ic_last_seen ON public.import_candidates (last_seen_at DESC);

ALTER TABLE public.import_candidates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "acesso autenticado" ON public.import_candidates
    FOR SELECT TO authenticated USING (true);

-- ── RPC: active candidates sorted by ETA ─────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_ic_active()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(row_to_json(x) ORDER BY x.eta NULLS LAST, x.confidence_score DESC), '[]'::json) FROM (
    SELECT
      ic.id, ic.imo, ic.mmsi, ic.navio, ic.flag,
      ic.ship_type, ic.ship_type_code, ic.length_m, ic.dwt,
      ic.destination_raw, ic.destination_slug, ic.destination_port_name, ic.eta,
      ic.origin_port_name, ic.origin_locode, ic.origin_country,
      ic.origin_is_product_hub, ic.departure_ts,
      ic.current_draught_m, ic.max_draught_m, ic.is_loaded,
      ic.confidence_score, ic.signals,
      ic.first_seen_at, ic.last_seen_at, ic.status, ic.in_lineup_since
    FROM public.import_candidates ic
    WHERE ic.status IN ('active', 'in_lineup')
  ) x;
$$;

-- ── RPC: summary counts per destination port + avg confidence ────────────────
CREATE OR REPLACE FUNCTION public.get_ic_summary()
RETURNS json LANGUAGE sql SECURITY DEFINER AS $$
  SELECT COALESCE(json_agg(row_to_json(x) ORDER BY x.destination_slug), '[]'::json) FROM (
    SELECT
      destination_slug,
      COUNT(*)::int AS candidates,
      COUNT(*) FILTER (WHERE status = 'in_lineup')::int AS in_lineup,
      COUNT(*) FILTER (WHERE status = 'active')::int AS active_only,
      ROUND(AVG(confidence_score))::int AS avg_confidence,
      SUM(dwt)::bigint AS total_dwt
    FROM public.import_candidates
    WHERE status IN ('active', 'in_lineup')
      AND destination_slug IS NOT NULL
    GROUP BY destination_slug
  ) x;
$$;

-- ── Trigger: when a navios_diesel row matching a candidate lands, auto-update
-- the candidate's status to 'in_lineup'. Match is by normalised name.
CREATE OR REPLACE FUNCTION public._match_candidate_on_navio_insert()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.import_candidates ic
  SET status = 'in_lineup',
      in_lineup_since = COALESCE(ic.in_lineup_since, NEW.collected_at)
  WHERE ic.status = 'active'
    AND (
      (NEW.imo  IS NOT NULL AND ic.imo  = NEW.imo)
      OR (NEW.mmsi IS NOT NULL AND ic.mmsi = NEW.mmsi)
      OR upper(regexp_replace(NEW.navio, '[^A-Za-z0-9]', '', 'g'))
         = upper(regexp_replace(ic.navio, '[^A-Za-z0-9]', '', 'g'))
    );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_match_candidate ON public.navios_diesel;
CREATE TRIGGER trg_match_candidate
    AFTER INSERT ON public.navios_diesel
    FOR EACH ROW
    EXECUTE FUNCTION public._match_candidate_on_navio_insert();

-- Seed: new module visibility row so admins can toggle per client
INSERT INTO public.module_visibility (module_slug, is_visible_for_clients)
VALUES ('navios-diesel-radar', true)
ON CONFLICT (module_slug) DO NOTHING;
