-- ============================================================================
-- SectorData — Full schema snapshot
-- Extracted from Supabase project rrrkgynlpqtmvuuqdjpb on 2026-03-27
-- Version: 1.0
-- ============================================================================

-- ── Table: vendas ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.vendas (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano             bigint,
    mes             bigint,
    agente_regulado text,
    nome_produto    text,
    regiao_destinatario text,
    uf_destino      text,
    mercado_destinatario text,
    quantidade_produto double precision,
    classificacao   text,
    date            date,
    segmento        text
);

-- ── Row Level Security ─────────────────────────────────────────────────────
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "acesso autenticado" ON public.vendas
    FOR SELECT TO authenticated USING (true);

-- ── Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_vendas_agente ON public.vendas USING btree (agente_regulado);
CREATE INDEX IF NOT EXISTS idx_vendas_agente_regulado ON public.vendas USING btree (agente_regulado);
CREATE INDEX IF NOT EXISTS idx_vendas_ano ON public.vendas USING btree (ano);
CREATE INDEX IF NOT EXISTS idx_vendas_classificacao ON public.vendas USING btree (classificacao);
CREATE INDEX IF NOT EXISTS idx_vendas_date ON public.vendas USING btree (date);
CREATE INDEX IF NOT EXISTS idx_vendas_mercado ON public.vendas USING btree (mercado_destinatario);
CREATE INDEX IF NOT EXISTS idx_vendas_mes ON public.vendas USING btree (mes);
CREATE INDEX IF NOT EXISTS idx_vendas_ms_serie ON public.vendas USING btree (date, nome_produto, segmento, classificacao);
CREATE INDEX IF NOT EXISTS idx_vendas_produto_segmento ON public.vendas USING btree (nome_produto, segmento);
CREATE INDEX IF NOT EXISTS idx_vendas_regiao ON public.vendas USING btree (regiao_destinatario);
CREATE INDEX IF NOT EXISTS idx_vendas_regiao_dest ON public.vendas USING btree (regiao_destinatario);
CREATE INDEX IF NOT EXISTS idx_vendas_uf ON public.vendas USING btree (uf_destino);
CREATE INDEX IF NOT EXISTS idx_vendas_uf_dest ON public.vendas USING btree (uf_destino);

-- ── Materialized Views ─────────────────────────────────────────────────────
CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_ms_serie AS
SELECT
    to_char(date_trunc('month', date::timestamp with time zone), 'YYYY-MM-DD') AS date,
    nome_produto,
    CASE WHEN segmento = 'Outros' THEN 'Retail' ELSE segmento END AS segmento,
    classificacao,
    agente_regulado,
    sum(quantidade_produto) AS quantidade
FROM vendas v
GROUP BY date_trunc('month', date::timestamp with time zone), nome_produto, segmento, classificacao, agente_regulado;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_ms_serie_fast AS
SELECT
    to_char(date_trunc('month', date::timestamp with time zone), 'YYYY-MM-DD') AS date,
    nome_produto,
    CASE WHEN segmento = 'Outros' THEN 'Retail' ELSE segmento END AS segmento,
    classificacao,
    sum(quantidade_produto) AS quantidade
FROM vendas v
GROUP BY date_trunc('month', date::timestamp with time zone), nome_produto, segmento, classificacao;

-- ── Materialized View Indexes ──────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS mv_ms_serie_pk ON public.mv_ms_serie USING btree (date, nome_produto, segmento, classificacao, agente_regulado);
CREATE INDEX IF NOT EXISTS mv_ms_serie_date_idx ON public.mv_ms_serie USING btree (date);
CREATE INDEX IF NOT EXISTS mv_ms_serie_classificacao_idx ON public.mv_ms_serie USING btree (classificacao);
CREATE INDEX IF NOT EXISTS mv_ms_serie_agente_regulado_idx ON public.mv_ms_serie USING btree (agente_regulado);
CREATE INDEX IF NOT EXISTS mv_ms_serie_nome_produto_segmento_idx ON public.mv_ms_serie USING btree (nome_produto, segmento);
CREATE INDEX IF NOT EXISTS idx_mv_ms_serie_fast_date ON public.mv_ms_serie_fast USING btree (date);

-- ── Functions ──────────────────────────────────────────────────────────────

-- Function: classificar_agentes
CREATE OR REPLACE FUNCTION public.classificar_agentes()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  SET LOCAL statement_timeout = 0;
  UPDATE vendas SET classificacao = CASE
    WHEN agente_regulado = 'VIBRA ENERGIA S.A'
      THEN 'Vibra'
    WHEN agente_regulado = 'IPIRANGA PRODUTOS DE PETRÓLEO S.A'
      THEN 'Ipiranga'
    WHEN agente_regulado IN (
      'RAIZEN S.A.',
      'RAIZEN MIME COMBUSTIVEIS S/A.',
      'PETRÓLEO SABBÁ S.A.',
      'CENTROESTE DISTRIBUICAO DE DERIVADOS DE PETROLEO S/A'
    ) THEN 'Raizen'
    ELSE 'Others'
  END
  WHERE true;
END;
$function$;

-- Function: fn_classificar_agente
CREATE OR REPLACE FUNCTION public.fn_classificar_agente()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.classificacao = CASE
    WHEN NEW.agente_regulado = 'VIBRA ENERGIA S.A'
      THEN 'Vibra'
    WHEN NEW.agente_regulado = 'IPIRANGA PRODUTOS DE PETRÓLEO S.A'
      THEN 'Ipiranga'
    WHEN NEW.agente_regulado IN (
      'RAIZEN S.A.',
      'RAIZEN MIME COMBUSTIVEIS S/A.',
      'PETRÓLEO SABBÁ S.A.',
      'CENTROESTE DISTRIBUICAO DE DERIVADOS DE PETROLEO S/A'
    ) THEN 'Raizen'
    ELSE 'Others'
  END;
  RETURN NEW;
END;
$function$;

-- Function: get_metricas
CREATE OR REPLACE FUNCTION public.get_metricas(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS json
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT json_build_object(
        'total_registros',  COUNT(*),
        'quantidade_total', COALESCE(SUM(quantidade_produto), 0),
        'anos_distintos',   COUNT(DISTINCT ano)
    )
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos));
$function$;

-- Function: get_metricas
CREATE OR REPLACE FUNCTION public.get_metricas(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS json
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT json_build_object(
    'total_registros', COUNT(*),
    'quantidade_total', SUM(quantidade_produto),
    'anos_distintos',  COUNT(DISTINCT ano)
)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
$function$;

-- Function: get_metricas
CREATE OR REPLACE FUNCTION public.get_metricas(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS json
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT json_build_object(
  'total_registros', COUNT(*),
  'quantidade_total', COALESCE(SUM(quantidade_produto), 0),
  'anos_distintos',  COUNT(DISTINCT ano)
) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
$function$;

-- Function: get_ms_opcoes_filtros
CREATE OR REPLACE FUNCTION public.get_ms_opcoes_filtros()
 RETURNS json
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT json_build_object(
    'datas',   (SELECT json_agg(d ORDER BY d)
                FROM (SELECT DISTINCT date AS d FROM mv_ms_serie) t),
    'regioes', (SELECT json_agg(DISTINCT regiao_destinatario ORDER BY regiao_destinatario)
                FROM vendas WHERE regiao_destinatario IS NOT NULL),
    'ufs',     (SELECT json_agg(DISTINCT uf_destino ORDER BY uf_destino)
                FROM vendas WHERE uf_destino IS NOT NULL),
    'mercados',(SELECT json_agg(DISTINCT mercado_destinatario ORDER BY mercado_destinatario)
                FROM vendas WHERE mercado_destinatario IS NOT NULL)
  );
$function$;

-- Function: get_ms_serie
CREATE OR REPLACE FUNCTION public.get_ms_serie(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_regioes text[] DEFAULT NULL::text[], p_ufs text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(date text, nome_produto text, segmento text, classificacao text, agente_regulado text, quantidade double precision)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF p_regioes IS NULL AND p_ufs IS NULL AND p_mercados IS NULL THEN
    RETURN QUERY
    SELECT m.date, m.nome_produto, m.segmento, m.classificacao,
           m.agente_regulado, m.quantidade
    FROM mv_ms_serie m
    WHERE (p_data_inicio IS NULL OR m.date >= p_data_inicio)
      AND (p_data_fim    IS NULL OR m.date <= p_data_fim);
  ELSE
    RETURN QUERY
    SELECT
      to_char(date_trunc('month', v.date), 'YYYY-MM-DD') AS date,
      v.nome_produto,
      CASE WHEN v.segmento = 'Outros' THEN 'Retail' ELSE v.segmento END,
      v.classificacao,
      v.agente_regulado,
      SUM(v.quantidade_produto)
    FROM vendas v
    WHERE (p_data_inicio IS NULL OR v.date >= p_data_inicio::date)
      AND (p_data_fim    IS NULL OR v.date <= p_data_fim::date)
      AND (p_regioes  IS NULL OR v.regiao_destinatario = ANY(p_regioes))
      AND (p_ufs      IS NULL OR v.uf_destino          = ANY(p_ufs))
      AND (p_mercados IS NULL OR v.mercado_destinatario = ANY(p_mercados))
    GROUP BY date_trunc('month', v.date), v.nome_produto, v.segmento,
             v.classificacao, v.agente_regulado;
  END IF;
END;
$function$;

-- Function: get_ms_serie_fast
CREATE OR REPLACE FUNCTION public.get_ms_serie_fast(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_regioes text[] DEFAULT NULL::text[], p_ufs text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(date text, nome_produto text, segmento text, classificacao text, quantidade double precision)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF p_regioes IS NULL AND p_ufs IS NULL AND p_mercados IS NULL THEN
    -- Usa a mesma mv_ms_serie que funciona, apenas agrega por classificacao
    RETURN QUERY
    SELECT m.date, m.nome_produto, m.segmento, m.classificacao,
           SUM(m.quantidade) AS quantidade
    FROM mv_ms_serie m
    WHERE (p_data_inicio IS NULL OR m.date >= p_data_inicio)
      AND (p_data_fim    IS NULL OR m.date <= p_data_fim)
    GROUP BY m.date, m.nome_produto, m.segmento, m.classificacao;
  ELSE
    RETURN QUERY
    SELECT
      to_char(date_trunc('month', v.date), 'YYYY-MM-DD') AS date,
      v.nome_produto,
      CASE WHEN v.segmento = 'Outros' THEN 'Retail' ELSE v.segmento END,
      v.classificacao,
      SUM(v.quantidade_produto)
    FROM vendas v
    WHERE (p_data_inicio IS NULL OR v.date >= p_data_inicio::date)
      AND (p_data_fim    IS NULL OR v.date <= p_data_fim::date)
      AND (p_regioes  IS NULL OR v.regiao_destinatario = ANY(p_regioes))
      AND (p_ufs      IS NULL OR v.uf_destino          = ANY(p_ufs))
      AND (p_mercados IS NULL OR v.mercado_destinatario = ANY(p_mercados))
    GROUP BY date_trunc('month', v.date), v.nome_produto, v.segmento,
             v.classificacao;
  END IF;
END;
$function$;

-- Function: get_ms_serie_others
CREATE OR REPLACE FUNCTION public.get_ms_serie_others(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_regioes text[] DEFAULT NULL::text[], p_ufs text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(date text, nome_produto text, segmento text, classificacao text, agente_regulado text, quantidade double precision)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF p_regioes IS NULL AND p_ufs IS NULL AND p_mercados IS NULL THEN
    RETURN QUERY
    SELECT m.date, m.nome_produto, m.segmento, m.classificacao,
           m.agente_regulado, m.quantidade
    FROM mv_ms_serie m
    WHERE (p_data_inicio IS NULL OR m.date >= p_data_inicio)
      AND (p_data_fim    IS NULL OR m.date <= p_data_fim)
      AND m.classificacao NOT IN ('Vibra', 'Ipiranga', 'Raizen');
  ELSE
    RETURN QUERY
    SELECT
      to_char(date_trunc('month', v.date), 'YYYY-MM-DD') AS date,
      v.nome_produto,
      CASE WHEN v.segmento = 'Outros' THEN 'Retail' ELSE v.segmento END,
      v.classificacao,
      v.agente_regulado,
      SUM(v.quantidade_produto)
    FROM vendas v
    WHERE (p_data_inicio IS NULL OR v.date >= p_data_inicio::date)
      AND (p_data_fim    IS NULL OR v.date <= p_data_fim::date)
      AND (p_regioes  IS NULL OR v.regiao_destinatario = ANY(p_regioes))
      AND (p_ufs      IS NULL OR v.uf_destino          = ANY(p_ufs))
      AND (p_mercados IS NULL OR v.mercado_destinatario = ANY(p_mercados))
      AND v.classificacao NOT IN ('Vibra', 'Ipiranga', 'Raizen')
    GROUP BY date_trunc('month', v.date), v.nome_produto, v.segmento,
             v.classificacao, v.agente_regulado;
  END IF;
END;
$function$;

-- Function: get_opcoes_filtros
CREATE OR REPLACE FUNCTION public.get_opcoes_filtros()
 RETURNS json
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT json_build_object(
        'datas',       (SELECT json_agg(d ORDER BY d) FROM (SELECT DISTINCT date::text AS d FROM vendas WHERE date IS NOT NULL) t),
        'agentes',     (SELECT json_agg(DISTINCT agente_regulado ORDER BY agente_regulado) FROM vendas WHERE agente_regulado IS NOT NULL),
        'regioes_dest',(SELECT json_agg(DISTINCT regiao_destinatario ORDER BY regiao_destinatario) FROM vendas WHERE regiao_destinatario IS NOT NULL),
        'ufs_dest',    (SELECT json_agg(DISTINCT uf_destino ORDER BY uf_destino) FROM vendas WHERE uf_destino IS NOT NULL),
        'mercados',    (SELECT json_agg(DISTINCT mercado_destinatario ORDER BY mercado_destinatario) FROM vendas WHERE mercado_destinatario IS NOT NULL)
    );
$function$;

-- Function: get_others_players
CREATE OR REPLACE FUNCTION public.get_others_players()
 RETURNS TABLE(agente_regulado text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT DISTINCT agente_regulado
  FROM mv_ms_serie
  WHERE classificacao NOT IN ('Vibra', 'Ipiranga', 'Raizen')
    AND agente_regulado IS NOT NULL
  ORDER BY agente_regulado;
$function$;

-- Function: get_qtd_por_agente
CREATE OR REPLACE FUNCTION public.get_qtd_por_agente(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS TABLE(agente text, quantidade double precision)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT agente_regulado, SUM(quantidade_produto)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY agente_regulado ORDER BY 2 DESC
$function$;

-- Function: get_qtd_por_agente
CREATE OR REPLACE FUNCTION public.get_qtd_por_agente(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(agente text, quantidade double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT agente_regulado, SUM(quantidade_produto) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos)) AND (p_meses IS NULL OR mes = ANY(p_meses)) AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes)) AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest)) AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest)) AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY agente_regulado ORDER BY 2 DESC
$function$;

-- Function: get_qtd_por_agente
CREATE OR REPLACE FUNCTION public.get_qtd_por_agente(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS TABLE(agente_regulado text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT agente_regulado, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos))
    GROUP BY agente_regulado ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_agente
CREATE OR REPLACE FUNCTION public.get_qtd_por_agente(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(agente_regulado text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT agente_regulado, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio  IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim     IS NULL OR date::text <= p_data_fim)
      AND (p_agentes      IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario  = ANY(p_regioes_dest))
      AND (p_ufs_dest     IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados     IS NULL OR mercado_destinatario = ANY(p_mercados))
    GROUP BY agente_regulado
    ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_ano
CREATE OR REPLACE FUNCTION public.get_qtd_por_ano(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS TABLE(ano bigint, quantidade double precision)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT ano, SUM(quantidade_produto)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY ano ORDER BY ano
$function$;

-- Function: get_qtd_por_ano
CREATE OR REPLACE FUNCTION public.get_qtd_por_ano(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(ano integer, quantidade double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT ano, SUM(quantidade_produto) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos)) AND (p_meses IS NULL OR mes = ANY(p_meses)) AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes)) AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest)) AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest)) AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY ano ORDER BY ano
$function$;

-- Function: get_qtd_por_ano
CREATE OR REPLACE FUNCTION public.get_qtd_por_ano(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS TABLE(ano integer, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT ano, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos))
    GROUP BY ano ORDER BY ano;
$function$;

-- Function: get_qtd_por_mes
CREATE OR REPLACE FUNCTION public.get_qtd_por_mes(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS TABLE(mes bigint, quantidade double precision)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT mes, SUM(quantidade_produto)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY mes ORDER BY mes
$function$;

-- Function: get_qtd_por_mes
CREATE OR REPLACE FUNCTION public.get_qtd_por_mes(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(mes integer, quantidade double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT mes, SUM(quantidade_produto) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos)) AND (p_meses IS NULL OR mes = ANY(p_meses)) AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes)) AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest)) AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest)) AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY mes ORDER BY mes
$function$;

-- Function: get_qtd_por_mes
CREATE OR REPLACE FUNCTION public.get_qtd_por_mes(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS TABLE(ano integer, mes integer, date text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT ano, mes, date::text, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos))
    GROUP BY ano, mes, date ORDER BY date;
$function$;

-- Function: get_qtd_por_produto
CREATE OR REPLACE FUNCTION public.get_qtd_por_produto(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS TABLE(nome_produto text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT nome_produto, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos))
    GROUP BY nome_produto ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_produto
CREATE OR REPLACE FUNCTION public.get_qtd_por_produto(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(nome_produto text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT nome_produto, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio  IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim     IS NULL OR date::text <= p_data_fim)
      AND (p_agentes      IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario  = ANY(p_regioes_dest))
      AND (p_ufs_dest     IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados     IS NULL OR mercado_destinatario = ANY(p_mercados))
    GROUP BY nome_produto
    ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_produto
CREATE OR REPLACE FUNCTION public.get_qtd_por_produto(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(produto text, quantidade double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT nome_produto, SUM(quantidade_produto) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos)) AND (p_meses IS NULL OR mes = ANY(p_meses)) AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes)) AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest)) AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest)) AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY nome_produto ORDER BY 2 DESC LIMIT 20
$function$;

-- Function: get_qtd_por_produto
CREATE OR REPLACE FUNCTION public.get_qtd_por_produto(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS TABLE(produto text, quantidade double precision)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT nome_produto, SUM(quantidade_produto)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY nome_produto ORDER BY 2 DESC LIMIT 20
$function$;

-- Function: get_qtd_por_regiao
CREATE OR REPLACE FUNCTION public.get_qtd_por_regiao(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS TABLE(regiao text, quantidade double precision)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT regiao_origem, SUM(quantidade_produto)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY regiao_origem ORDER BY 2 DESC
$function$;

-- Function: get_qtd_por_regiao
CREATE OR REPLACE FUNCTION public.get_qtd_por_regiao(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(regiao text, quantidade double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT regiao_destinatario, SUM(quantidade_produto) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos)) AND (p_meses IS NULL OR mes = ANY(p_meses)) AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes)) AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest)) AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest)) AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY regiao_destinatario ORDER BY 2 DESC
$function$;

-- Function: get_qtd_por_regiao
CREATE OR REPLACE FUNCTION public.get_qtd_por_regiao(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS TABLE(regiao_destinatario text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT regiao_destinatario, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos))
    GROUP BY regiao_destinatario ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_regiao
CREATE OR REPLACE FUNCTION public.get_qtd_por_regiao(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(regiao_destinatario text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT regiao_destinatario, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio  IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim     IS NULL OR date::text <= p_data_fim)
      AND (p_agentes      IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario  = ANY(p_regioes_dest))
      AND (p_ufs_dest     IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados     IS NULL OR mercado_destinatario = ANY(p_mercados))
    GROUP BY regiao_destinatario
    ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_uf
CREATE OR REPLACE FUNCTION public.get_qtd_por_uf(p_anos integer[], p_meses integer[], p_agentes text[], p_regioes_origem text[], p_ufs_origem text[], p_regioes_dest text[], p_ufs_dest text[], p_mercados text[])
 RETURNS TABLE(uf text, quantidade double precision)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
SELECT uf_origem, SUM(quantidade_produto)
FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos))
  AND (p_meses IS NULL OR mes = ANY(p_meses))
  AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes))
  AND (p_regioes_origem IS NULL OR regiao_origem = ANY(p_regioes_origem))
  AND (p_ufs_origem IS NULL OR uf_origem = ANY(p_ufs_origem))
  AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
  AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest))
  AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY uf_origem ORDER BY 2 DESC
$function$;

-- Function: get_qtd_por_uf
CREATE OR REPLACE FUNCTION public.get_qtd_por_uf(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(uf_destino text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT uf_destino, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio  IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim     IS NULL OR date::text <= p_data_fim)
      AND (p_agentes      IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario  = ANY(p_regioes_dest))
      AND (p_ufs_dest     IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados     IS NULL OR mercado_destinatario = ANY(p_mercados))
    GROUP BY uf_destino
    ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- Function: get_qtd_por_uf
CREATE OR REPLACE FUNCTION public.get_qtd_por_uf(p_anos integer[] DEFAULT NULL::integer[], p_meses integer[] DEFAULT NULL::integer[], p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[])
 RETURNS TABLE(uf text, quantidade double precision)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
SELECT uf_destino, SUM(quantidade_produto) FROM vendas
WHERE (p_anos IS NULL OR ano = ANY(p_anos)) AND (p_meses IS NULL OR mes = ANY(p_meses)) AND (p_agentes IS NULL OR agente_regulado = ANY(p_agentes)) AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest)) AND (p_ufs_dest IS NULL OR uf_destino = ANY(p_ufs_dest)) AND (p_mercados IS NULL OR mercado_destinatario = ANY(p_mercados))
GROUP BY uf_destino ORDER BY 2 DESC
$function$;

-- Function: get_qtd_por_uf
CREATE OR REPLACE FUNCTION public.get_qtd_por_uf(p_data_inicio text DEFAULT NULL::text, p_data_fim text DEFAULT NULL::text, p_agentes text[] DEFAULT NULL::text[], p_regioes_dest text[] DEFAULT NULL::text[], p_ufs_dest text[] DEFAULT NULL::text[], p_mercados text[] DEFAULT NULL::text[], p_segmentos text[] DEFAULT NULL::text[])
 RETURNS TABLE(uf_destino text, quantidade numeric)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT uf_destino, ROUND(SUM(quantidade_produto)::numeric, 2)
    FROM vendas
    WHERE (p_data_inicio IS NULL OR date::text >= p_data_inicio)
      AND (p_data_fim    IS NULL OR date::text <= p_data_fim)
      AND (p_agentes     IS NULL OR agente_regulado      = ANY(p_agentes))
      AND (p_regioes_dest IS NULL OR regiao_destinatario = ANY(p_regioes_dest))
      AND (p_ufs_dest    IS NULL OR uf_destino           = ANY(p_ufs_dest))
      AND (p_mercados    IS NULL OR mercado_destinatario = ANY(p_mercados))
      AND (p_segmentos   IS NULL OR segmento             = ANY(p_segmentos))
    GROUP BY uf_destino ORDER BY SUM(quantidade_produto) DESC;
$function$;

-- ── Triggers ──────────────────────────────────────────────────────────────
CREATE TRIGGER trg_classificar_agente
    BEFORE INSERT OR UPDATE OF agente_regulado ON public.vendas
    FOR EACH ROW EXECUTE FUNCTION fn_classificar_agente();
