-- ============================================================================
-- Price Bands — table, indexes, RLS, RPC function
-- Run this in the Supabase Dashboard SQL editor.
-- ============================================================================

-- ── Table ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.price_bands (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date                        DATE    NOT NULL,
  product                     TEXT    NOT NULL,   -- 'Gasoline' | 'Diesel'
  bba_import_parity           NUMERIC(10,4),      -- IBBA for Gasoline, BBA for Diesel
  bba_import_parity_w_subsidy NUMERIC(10,4),      -- Diesel only
  bba_export_parity           NUMERIC(10,4),
  petrobras_price             NUMERIC(10,4),
  petrobras_price_w_subsidy   NUMERIC(10,4),      -- reserved, not yet used
  UNIQUE(product, date)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_pb_product_date
  ON public.price_bands (product, date);

-- ── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.price_bands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "acesso autenticado" ON public.price_bands
  FOR SELECT TO authenticated USING (true);

-- ── RPC: all rows for one (or all) products, ordered by date ─────────────────
CREATE OR REPLACE FUNCTION public.get_price_bands_data(
  p_product text DEFAULT NULL
)
RETURNS SETOF public.price_bands
LANGUAGE sql
SECURITY DEFINER AS $$
  SELECT *
  FROM public.price_bands
  WHERE (p_product IS NULL OR product = p_product)
  ORDER BY date;
$$;
